import React from 'react'

const TermsAndConditions = () => {
  return (
    <section class="inner-page">
      <div class="container">
        <p>ARBITRATION AND CLASS ACTION AND JURY WAIVER NOTICE PARTIAL SUMMARY: YOU AGREE THAT EXCEPT FOR CERTAIN TYPES OF DISPUTES DESCRIBED IN THE ARBITRATION AGREEMENT, DISPUTES BETWEEN YOU AND COMPANY WILL BE RESOLVED BY MANDATORY BINDING INDIVIDUAL ARBITRATION, AND YOU WAIVE ANY RIGHT TO PARTICIPATE IN A CLASS- ACTION LAWSUIT OR CLASS-WIDE ARBITRATION, CONSOLIDATION, COURT PROCEEDING, OR JURY TRIAL, ALL AS SET FORTH IN THE IMPORTANT ARBITRATION AGREEMENT (A DISTINCT AGREEMENT WITHIN, AND DEMARCATED AT WHAT IS HEADED SECTIONS 17 and 118 ).MODIFICATION NOTICE SUMMARY: WE HAVE THE RIGHT TO MODIFY THIS AGREEMENT, EFFECTIVE IMMEDIATELY, AT ANY TIME AND WITHOUT NOTICE OTHER THAN POSTING THE MODIFIED AGREEMENT. IF ANY MODIFICATION IS UNACCEPTABLE TO YOU, YOU SHALL CEASE USING ANY COMPANY WEBSITE, SERVICES, OR PLATFORM. IF YOU DO NOT CEASE USING ANY COMPANY WEBSITE, SERVICES, OR PLATFORM YOU WILL BE CONCLUSIVELY DEEMED TO HAVE AGREED TO AND ACCEPTED THE MODIFICATION(S).COMPANY DOES NOT AND WILL NOT EVER GIVE OR OFFER LEGAL ADVICE, AND DOES NOT AND CANNOT GUARANTEE THE ACCURACY OR SUITABILITY OF ITS CONTENT OR COMMUNICATIONS FOR A PARTICULAR PURPOSE.</p>
        <h2>Introduction</h2>
        <p>LEGAL CONTRACT. This legal and binding contract is referred to as “Terms,” “Agreement,” or “Contract.” By entering into it You acknowledge that You will have read, and have in fact read, and understand, and agree to and with all of it. The Terms apply to your access to and use of www.bambee.com and to Bambee’s websites (desktop and mobile) (“Website(s),” or “Site(s)”), applications, apps, and all means of written and oral communications, including emails, chats, instant messengering, and the like, and voice communications (referred to herein individually and collectively, including Websites or Sites, as “Platforms ” or “Platform”). These Platforms and Bambee are owned and/or operated by or for Bambee, Inc., and/or one or more of its subsidiaries (“Company,” “Us,” “We,” “Our”). Your accessing or using any Services or Platform is Your agreement and is deemed to be your agreement that you have the ability to and consent to enter into contractual agreements electronically. YOU ACKNOWLEDGE THAT YOUR accessing or using any Services or Platform, including whether or not you click the “Continue Button,” CONSTITUTES YOUR WRITTEN AGREEMENT AND ELECTRONIC SIGNATURE AND YOUR INTENT TO BE CONTRACTUALLY AND LEGALLY BOUND BY AND TO THE TERMS HEREIN.</p>
        <p>This Agreement contains the Terms that govern your access to any Platform and the use of, and the terms and conditions upon which Company will provide to you certain human resource management resources and other related services through our Platforms (collectively, the “Services,” “Platform,” or “Platforms”). This is a binding legal contract between you and the Company, so please read this Agreement and all related information referenced by this Agreement carefully before continuing to use any Platform, or registering for and/or using any of the Services. This Agreement is applicable to all persons, organizations, and entities, who or which use or access any Platform or Services, in their entity’s/company’s capacity or on an individual capacity, including users authorized by the employer to represent the employer, its employees, or other persons using or accessing any Platform or the Services (collectively, “User,” “User’s,” “You,” or “Your,” whether upper- case [capitalized] or lower-case). You are a United States of America resident and an individual of at least 18 years of age. If you are agreeing to this Agreement on behalf of a of any entity – including, but not limited to, a company, organization, association, or trust, for example, no matter the legal form of the entity ("entity"), you represent and warrant You are at least 18 years old, that you have authority to bind that entity to this Agreement, and your agreement to these Terms will be treated as the agreement of the entity and the entity agrees to be bound by You to the Terms. In that event, “you” and “your” refer to that entity. If you do not agree to these Terms, you may not access or use any Platform.</p>
            <p>Company reserves the right in its sole and unfettered discretion at any time to modify the Terms from time to time without notice to you and to impose new or additional terms or conditions on your use of Services or any Platform. Company may optionally notify you of any such change by sending an email message to the Administrator email address provided to Company upon Registration by User. Such modifications and additional terms and conditions will be effective immediately and incorporated into this Agreement. Your continued use of the Services will be deemed acceptance thereof. Except as posted by Us, including to the Websites or any Platform, the Terms will not be otherwise amended, and no terms will be waived by Us, except in a writing, hand signed by pen on paper by You and an authorized representative of Ours who intends to do so. For purposes specifically of this provision regarding any so-called amendment or waiver of the Terms, a "writing" does not include an email message, text, chat, or the like, sent from any device existing now or later developed and a signature does not include an electronic signature. For certainty, Your electronic Signature to this Agreement does constitute an electronic signature and it and this is a writing. We are not obligated to provide notice of modifications or amendment to the Terms by way of any method other than the making available or posting of the amended Terms on or through any Company Website(s) or Platform, and doing so without more is deemed and agreed to be sufficient notice of modifications and amendment(s). We may note on the Agreement available at or on or through Websites or Platforms, what the effective date of that version of the Terms is, and You agree that You will keep track Yourself of the effective dates of various versions of the Terms, and that We are not required to point out to You changes from version to version of the Terms. You may copy and paste each version of the Terms into a document for Your own personal retention, and You may use any variety of tools to "compare" various versions of the Terms. You should check these Terms regularly and periodically for modifications. The provisions contained herein supersede all previous notices or statements regarding our Terms with respect to any Platform. We may include the revised date and effective date of our Terms either at the top, bottom, or within the revised Terms. We encourage you to check our Websites frequently to see the current Terms in effect and any changes that may have been made to the Terms. By using any Platform following any modifications to the Terms, you agree to be bound by such modifications.</p>
            <p>Please also refer to the Company Privacy Policy, and any other terms accepted when Registering with Company, each of which are/is incorporated herein by reference. We are not governed by HIPAA (the Health Insurance Portability and Accountability Act); therefore, although we do protect data as described elsewhere, if You are governed by HIPAA we urge You to govern yourself accordingly. If HIPAA applies to You You will not disclose to Company or store with Company protected health information or personally identifiable health information (PHI).</p>
            <p>
                USE OF SERVICES / PLATFORMS Company’s service Platforms are licensed and provided to you subject to the terms and conditions, and your covenants, warranties and representations, set forth in this Agreement, and in any acknowledgment for specific Services / Platform(s). You agree that all information submitted or communicated by you to any Company Platform is and will be true and correct. You agree that any Platform you access constitutes confidential, proprietary, intellectual property of Company, that this license is revocable by Company at any time, and that you will not modify, reverse engineer, decompile or disassemble, or otherwise tamper with any Platform or create any derivative works or otherwise incorporate any Platform in other programs, without Company’s prior written consent. Any feedback, including modifications to any documents, you provide will become Company information and Company will have the royalty-free right to use and share the feedback and to create and use derivative works based on the feedback.</p>
                <p>The Company provides you with access to and use of any Platform subject to your compliance with the Terms. No material from any Platform may be copied, reproduced, republished, uploaded, posted, transmitted or distributed in any way, except for as specifically allowed by the Terms</p>
                <p>You grant us a non-exclusive, royalty-free license to use any feedback, content, or modification, you post on any Platform, or provide to Company, for any purpose, subject to the express terms of this Agreement.</p>

      </div>
      
    </section>
  )
}

export default TermsAndConditions